title: translating-for-raspberry-pi-corporate
hero_image: images/banner.png
description: translating-for-raspberry-pi-corporate description
version: 4
listed: false
copyedit: false
last_tested: "2019-06-03"
steps:
  - title: Introduction
  - title: Step title
  - title: What next?
