title: Translating for the Raspberry Pi Foundation
hero_image: images/banner.png
description: getting-started-with-translation description
version: 4
listed: false
copyedit: false
last_tested: "2019-01-23"
steps:
  - title: Introduction
  - title: What we translate
  - title: Workflow
  - title: Tools
  - title: Support
  - title: Recognition scheme
  - title: Next steps
